from enum import Enum


class LLMModel(Enum):
    GEMINI_PRO="gemini-pro"
    GEMINI_PRO_VISION="gemini-pro-vision"
    GEMINI_FLASH="gemini-flash"
    GEMINI_FLASH_VISION="gemini-flash-vision"
    GEMINI_2.5_FLASH="gemini-2.5-flash"
    GEMINI_2.5_FLASH_VISION="gemini-2.5-flash-vision"
    GEMINI_2.5_PRO="gemini-2.5-pro"
    GEMINI_2.5_PRO_VISION="gemini-2.5-pro-vision"
    GEMINI_2.5_FLASH_LITE="gemini-2.5-flash-lite"
    GEMINI_2.5_FLASH_LITE_VISION="gemini-2.5-flash-lite-vision"
    OPEN_AI_GPT_4="gpt-4"
    OPEN_AI_GPT_4_VISION="gpt-4-vision"
    OPEN_AI_GPT_4_LITE="gpt-4-lite"
    OPEN_AI_GPT_4_LITE_VISION="gpt-4-lite-vision"
    OPEN_AI_GPT_4_LITE_PRO="gpt-4-lite-pro"
    OPEN_AI_GPT_4_LITE_PRO_VISION="gpt-4-lite-pro-vision"
    OPEN_AI_GPT_4_LITE_PRO_VISION="gpt-4-lite-pro-vision"
    CLAUDE_SONNET="claude-sonnet"
    CLAUDE_SONNET_VISION="claude-sonnet-vision"
    CLAUDE_SONNET_LITE="claude-sonnet-lite"
    CLAUDE_SONNET_LITE_VISION="claude-sonnet-lite-vision"
    CLAUDE_SONNET_LITE_PRO="claude-sonnet-lite-pro"
    CLAUDE_SONNET_LITE_PRO_VISION="claude-sonnet-lite-pro-vision"
    COHERE_COMMAND="cohere-command"
    COHERE_COMMAND_VISION="cohere-command-vision"
    COHERE_COMMAND_LITE="cohere-command-lite"
    COHERE_COMMAND_LITE_VISION="cohere-command-lite-vision"
    COHERE_COMMAND_LITE_PRO="cohere-command-lite-pro"
    COHERE_COMMAND_LITE_PRO_VISION="cohere-command-lite-pro-vision"
    GROK_4="grok-4"
    GROK_4_VISION="grok-4-vision"
    GROK_4_LITE="grok-4-lite"
    GROK_4_LITE_VISION="grok-4-lite-vision"
    GROK_4_LITE_PRO="grok-4-lite-pro"
    LLAMA_3="llama-3"
    LLAMA_3_VISION="llama-3-vision"
    LLAMA_3_LITE="llama-3-lite"
    LLAMA_3_LITE_VISION="llama-3-lite-vision"
    LLAMA_3_LITE_PRO="llama-3-lite-pro"
    
    class OpenAiEnums(Enum):
        SYSTEM="system"
        USER="user"
        ASSISTANT="assistant"
    
